<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{8c3fea05-08d9-4bdc-b5eb-0bd792ace699}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	A1: Achse1;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[A1();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>